#!/usr/bin/env python3
# coding: utf-8


"""
Triangular, Pentagonal, and Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
        Triangle     Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
        Pentagonal   Pn=n(3n-1)/2    1, 5, 12, 22, 35, ...
        Hexagonal    Hn=n(2n-1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
"""


ANSWER = 1533776805


def triangle(n: int) -> int:
    """
    Triangle number
    """
    return n * (n + 1) // 2


def pentagonal(n: int) -> int:
    """
    Pentagonal number
    """
    return n * (3 * n - 1) // 2


def hexagonal(n: int) -> int:
    """
    Hexagonal number
    """
    return n * (2 * n - 1)


def solve() -> int:
    ti, pi, hi = 286, 166, 144
    tn, pn, hn = triangle(ti), pentagonal(pi), hexagonal(hi)

    while hn != tn or hn != pn:
        if tn < hn:
            ti += 1
            tn = triangle(ti)

        if pn < hn:
            pi += 1
            pn = pentagonal(pi)

        if hn < tn or hn < pn:
            hi += 1
            hn = hexagonal(hi)

    return tn
