#!/usr/bin/env python3
# coding: utf-8


"""
Cyclical Figurate Numbers

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate
(polygonal) numbers and are generated by the following formulae:

Triangle:   P(3,n) = n(n+1)/2,      1, 3, 6, 10, ...
Square:     P(4,n) = n^2            1, 4, 9, 16, ...
Pentagonal: P(5,n) = n(3n-1)/2      1, 5, 12, 22, ...
Hexagonal:  P(6,n) = n(2n-1)        1, 6, 15, 28, ...
Heptagonal: P(7,n) = n(5n-3)/2      1, 7, 18, 34, ...
Octagonal:  P(8,n) = n(3n-2)        1, 8, 21, 40, ...


The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

1. The set is cyclic, in that the last two digits of each number is the first two digits of
the next number (including the last number with the first).
2. Each polygonal type: triangle (P(3, 127) = 8128), square (P(4, 91) = 8281), and pentagonal
(P(5, 44) = 2882), is represented by a different number in the set.
3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type:
triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different
number in the set.
"""

from typing import Generator


ANSWER = 28684

LOWER_LIMIT = 1000
UPPER_LIMIT = 10000


def gen_triangle(lower: int, upper: int) -> Generator[int, None, None]:
    """
    Generate triangle numbers up to limit.
    """
    n = 1
    while True:
        num = n * (n + 1) // 2
        if num > upper:
            break

        if lower <= num < upper:
            yield num

        n += 1

def gen_square(lower: int, upper: int) -> Generator[int, None, None]:
    """
    Generate square numbers up to limit.
    """
    n = 1
    while True:
        num = n * n
        if num > upper:
            break

        if lower <= num < upper:
            yield num

        n += 1

def gen_pentagonal(lower: int, upper: int) -> Generator[int, None, None]:
    """
    Generate pentagonal numbers up to limit.
    """
    n = 1
    while True:
        num = n * (3 * n - 1) // 2
        if num > upper:
            break

        if lower <= num < upper:
            yield num

        n += 1


def gen_hexagonal(lower: int, upper: int) -> Generator[int, None, None]:
    """
    Generate hexagonal numbers up to limit.
    """
    n = 1
    while True:
        num = n * (2 * n - 1)
        if num > upper:
            break

        if lower <= num < upper:
            yield num

        n += 1

def gen_heptagonal(lower: int, upper: int) -> Generator[int, None, None]:
    """
    Generate heptagonal numbers up to limit.
    """
    n = 1
    while True:
        num = n * (5 * n - 3) // 2
        if num > upper:
            break

        if lower <= num < upper:
            yield num

        n += 1


def gen_octagonal(lower: int, upper: int) -> Generator[int, None, None]:
    """
    Generate octagonal numbers up to limit.
    """
    n = 1
    while True:
        num = n * (3 * n - 2)
        if num > upper:
            break

        if lower <= num < upper:
            yield num

        n += 1


def find_position(n: int, num_sets: list[set[int]]) -> int:
    """
    Find the position of num in the polygonal numbers.
    """
    result = 0

    for i, num_set in enumerate(num_sets):
        if n in num_set:
            result |= 1 << i

    return result


def find_position_list(nums: list[int], num_sets: list[set[int]]) -> int:
    """
    Find the position list of nums in the polygonal numbers.
    """
    result = 0

    for n in nums:
        result |= find_position(n, num_sets)

    return result


def find_cyclic(
        nums: list[int], num_sets: list[set[int]], prev: list[int] | None = None
    ) -> Generator[list[int], None, None]:
    """
    Find cyclic numbers.
    """
    if prev is None:
        prev = []

    if len(prev) == len(num_sets):
        if prev[0] // 100 == prev[-1] % 100:
            # print(f"found cyclic: {prev}")
            yield prev
        return

    prev_pos = find_position_list(prev, num_sets)
    for n in nums:
        l = prev + [n]
        if len(prev) <= 0:
            # print(f"trying: [{n}]: {l}")
            yield from find_cyclic(nums, num_sets, l)

        else:
            if l[-2] % 100 == l[-1] // 100:
                n_pos = find_position(n, num_sets)
                if n_pos | prev_pos > prev_pos:
                    # print(f"trying: [{n}] {l}")
                    yield from find_cyclic(nums, num_sets, l)


def solve() -> int:
    """
    Solve the problem.
    """
    triangle = set(gen_triangle(LOWER_LIMIT, UPPER_LIMIT))
    square = set(gen_square(LOWER_LIMIT, UPPER_LIMIT))
    pentagonal = set(gen_pentagonal(LOWER_LIMIT, UPPER_LIMIT))
    hexagonal = set(gen_hexagonal(LOWER_LIMIT, UPPER_LIMIT))
    heptagonal = set(gen_heptagonal(LOWER_LIMIT, UPPER_LIMIT))
    octagonal = set(gen_octagonal(LOWER_LIMIT, UPPER_LIMIT))

    num_sets = [triangle, square, pentagonal, hexagonal, heptagonal, octagonal]
    nums = list(triangle | square | pentagonal | hexagonal | heptagonal | octagonal)
    nums.sort()

    # print(f"triangle: {len(triangle)} {triangle}")
    # print(f"square: {len(square)} {square}")
    # print(f"pentagonal: {len(pentagonal)} {pentagonal}")
    # print(f"hexagonal: {len(hexagonal)} {hexagonal}")
    # print(f"heptagonal: {len(heptagonal)} {heptagonal}")
    # print(f"octagonal: {len(octagonal)} {octagonal}")
    # print("--------")

    result = 0
    for cyclic in find_cyclic(nums, num_sets):
        result = sum(cyclic)
        break

    return result
