# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-check:
    name: Run check on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.11"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Show runner info
      if: matrix.os == 'ubuntu-latest'
      run: |
        cat /proc/cpuinfo | grep model
        free
    - name: Analysing the code with pylint
      if: matrix.os == 'ubuntu-latest'
      run: |
        pylint --score=yes \
                --fail-under=9.9 \
                $(git ls-files '*.py')
    - name: Analysing the code with pylint
      if: matrix.os == 'windows-latest'
      run: |
        pylint --score=yes `
                --fail-under=9.9 `
                $(git ls-files '*.py')
    - name: Run on all solutions
      run: |
        python projeuler.py run -c
